# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'annoytator_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1442, 731)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.videoDisplayFrame = QtWidgets.QFrame(self.centralwidget)
        self.videoDisplayFrame.setGeometry(QtCore.QRect(20, 40, 631, 501))
        self.videoDisplayFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.videoDisplayFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.videoDisplayFrame.setObjectName("videoDisplayFrame")
        self.frameViewLabel = QtWidgets.QLabel(self.videoDisplayFrame)
        self.frameViewLabel.setGeometry(QtCore.QRect(10, 10, 611, 481))
        self.frameViewLabel.setText("")
        self.frameViewLabel.setScaledContents(True)
        self.frameViewLabel.setObjectName("frameViewLabel")
        self.loadVideoButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadVideoButton.setGeometry(QtCore.QRect(260, 620, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loadVideoButton.setFont(font)
        self.loadVideoButton.setObjectName("loadVideoButton")
        self.prevFrameButton = QtWidgets.QPushButton(self.centralwidget)
        self.prevFrameButton.setGeometry(QtCore.QRect(70, 620, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.prevFrameButton.setFont(font)
        self.prevFrameButton.setObjectName("prevFrameButton")
        self.nextFrameButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextFrameButton.setGeometry(QtCore.QRect(480, 620, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nextFrameButton.setFont(font)
        self.nextFrameButton.setObjectName("nextFrameButton")
        self.goToFrameButton = QtWidgets.QPushButton(self.centralwidget)
        self.goToFrameButton.setGeometry(QtCore.QRect(320, 560, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.goToFrameButton.setFont(font)
        self.goToFrameButton.setObjectName("goToFrameButton")
        self.videoDescLabel = QtWidgets.QLabel(self.centralwidget)
        self.videoDescLabel.setGeometry(QtCore.QRect(20, 20, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.videoDescLabel.setFont(font)
        self.videoDescLabel.setObjectName("videoDescLabel")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(680, 40, 731, 641))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.annotationView = QtWidgets.QTableView(self.tab)
        self.annotationView.setGeometry(QtCore.QRect(10, 10, 701, 431))
        self.annotationView.setShowGrid(True)
        self.annotationView.setObjectName("annotationView")
        self.loadAnnotationButton = QtWidgets.QPushButton(self.tab)
        self.loadAnnotationButton.setGeometry(QtCore.QRect(10, 450, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loadAnnotationButton.setFont(font)
        self.loadAnnotationButton.setObjectName("loadAnnotationButton")
        self.addEventsButton = QtWidgets.QPushButton(self.tab)
        self.addEventsButton.setGeometry(QtCore.QRect(280, 450, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addEventsButton.setFont(font)
        self.addEventsButton.setObjectName("addEventsButton")
        self.eventListWidget = QtWidgets.QListWidget(self.tab)
        self.eventListWidget.setGeometry(QtCore.QRect(420, 450, 291, 151))
        self.eventListWidget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.eventListWidget.setObjectName("eventListWidget")
        self.saveAnnotationButton = QtWidgets.QPushButton(self.tab)
        self.saveAnnotationButton.setGeometry(QtCore.QRect(12, 527, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.saveAnnotationButton.setFont(font)
        self.saveAnnotationButton.setObjectName("saveAnnotationButton")
        self.deleteEventsButton = QtWidgets.QPushButton(self.tab)
        self.deleteEventsButton.setGeometry(QtCore.QRect(280, 530, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.deleteEventsButton.setFont(font)
        self.deleteEventsButton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.deleteEventsButton.setObjectName("deleteEventsButton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.xCoorBox = QtWidgets.QComboBox(self.tab_2)
        self.xCoorBox.setGeometry(QtCore.QRect(180, 500, 161, 41))
        self.xCoorBox.setObjectName("xCoorBox")
        self.xCoorLabel = QtWidgets.QLabel(self.tab_2)
        self.xCoorLabel.setGeometry(QtCore.QRect(180, 480, 81, 16))
        self.xCoorLabel.setObjectName("xCoorLabel")
        self.yCoorLabel = QtWidgets.QLabel(self.tab_2)
        self.yCoorLabel.setGeometry(QtCore.QRect(360, 480, 91, 16))
        self.yCoorLabel.setObjectName("yCoorLabel")
        self.yCoorBox = QtWidgets.QComboBox(self.tab_2)
        self.yCoorBox.setGeometry(QtCore.QRect(360, 500, 171, 41))
        self.yCoorBox.setObjectName("yCoorBox")
        self.displayDataButton = QtWidgets.QPushButton(self.tab_2)
        self.displayDataButton.setGeometry(QtCore.QRect(550, 500, 121, 41))
        self.displayDataButton.setObjectName("displayDataButton")
        self.loadDataButton = QtWidgets.QPushButton(self.tab_2)
        self.loadDataButton.setGeometry(QtCore.QRect(50, 500, 111, 41))
        self.loadDataButton.setObjectName("loadDataButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 701, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.plotLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.plotLayout.setContentsMargins(0, 0, 0, 0)
        self.plotLayout.setObjectName("plotLayout")
        self.frameSlider = QtWidgets.QSlider(self.tab_2)
        self.frameSlider.setGeometry(QtCore.QRect(60, 450, 611, 22))
        self.frameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.frameSlider.setObjectName("frameSlider")
        self.connectVideoBox = QtWidgets.QCheckBox(self.tab_2)
        self.connectVideoBox.setGeometry(QtCore.QRect(50, 560, 221, 31))
        self.connectVideoBox.setObjectName("connectVideoBox")
        self.displayEventsBox = QtWidgets.QCheckBox(self.tab_2)
        self.displayEventsBox.setGeometry(QtCore.QRect(450, 560, 221, 20))
        self.displayEventsBox.setObjectName("displayEventsBox")
        self.tabWidget.addTab(self.tab_2, "")
        self.frameNumberEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.frameNumberEdit.setGeometry(QtCore.QRect(480, 560, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frameNumberEdit.setFont(font)
        self.frameNumberEdit.setObjectName("frameNumberEdit")
        self.videoDescLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.videoDescLabel_2.setGeometry(QtCore.QRect(680, 20, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.videoDescLabel_2.setFont(font)
        self.videoDescLabel_2.setObjectName("videoDescLabel_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1442, 26))
        self.menubar.setObjectName("menubar")
        self.menuFIle = QtWidgets.QMenu(self.menubar)
        self.menuFIle.setObjectName("menuFIle")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuAnnotations = QtWidgets.QMenu(self.menubar)
        self.menuAnnotations.setObjectName("menuAnnotations")
        self.menuVideo = QtWidgets.QMenu(self.menubar)
        self.menuVideo.setObjectName("menuVideo")
        self.menuData = QtWidgets.QMenu(self.menubar)
        self.menuData.setObjectName("menuData")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionSave_as_2 = QtWidgets.QAction(MainWindow)
        self.actionSave_as_2.setObjectName("actionSave_as_2")
        self.actionAutosave = QtWidgets.QAction(MainWindow)
        self.actionAutosave.setCheckable(True)
        self.actionAutosave.setObjectName("actionAutosave")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionSettings_2 = QtWidgets.QAction(MainWindow)
        self.actionSettings_2.setObjectName("actionSettings_2")
        self.actionSettings_3 = QtWidgets.QAction(MainWindow)
        self.actionSettings_3.setObjectName("actionSettings_3")
        self.menuFIle.addAction(self.actionSave)
        self.menuFIle.addAction(self.actionSave_as)
        self.menuFIle.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionAbout)
        self.menuAnnotations.addAction(self.actionSettings_2)
        self.menuAnnotations.addAction(self.actionSave_as_2)
        self.menuAnnotations.addAction(self.actionAutosave)
        self.menuVideo.addAction(self.actionSettings_3)
        self.menuData.addAction(self.actionSettings)
        self.menubar.addAction(self.menuFIle.menuAction())
        self.menubar.addAction(self.menuVideo.menuAction())
        self.menubar.addAction(self.menuAnnotations.menuAction())
        self.menubar.addAction(self.menuData.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Annoytator"))
        self.loadVideoButton.setStatusTip(_translate("MainWindow", "Load video file"))
        self.loadVideoButton.setText(_translate("MainWindow", "Load video"))
        self.prevFrameButton.setStatusTip(_translate("MainWindow", "Move back 1 frame (hotkey: S) [use A to move 10 frames]"))
        self.prevFrameButton.setText(_translate("MainWindow", "<<"))
        self.nextFrameButton.setStatusTip(_translate("MainWindow", "Move forward 1 frame (hotkey: D) [Use F to move 10 frames]"))
        self.nextFrameButton.setText(_translate("MainWindow", ">>"))
        self.goToFrameButton.setStatusTip(_translate("MainWindow", "Go to given frame"))
        self.goToFrameButton.setText(_translate("MainWindow", "Go to frame:"))
        self.videoDescLabel.setText(_translate("MainWindow", "Video"))
        self.loadAnnotationButton.setStatusTip(_translate("MainWindow", "Load existing annotations"))
        self.loadAnnotationButton.setText(_translate("MainWindow", "Load annotations"))
        self.addEventsButton.setStatusTip(_translate("MainWindow", "Add events to list"))
        self.addEventsButton.setText(_translate("MainWindow", "Add event"))
        self.saveAnnotationButton.setStatusTip(_translate("MainWindow", "Save annotations"))
        self.saveAnnotationButton.setText(_translate("MainWindow", "Save annotations"))
        self.deleteEventsButton.setStatusTip(_translate("MainWindow", "Delete events from list"))
        self.deleteEventsButton.setText(_translate("MainWindow", "Delete event"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Annotations"))
        self.xCoorLabel.setText(_translate("MainWindow", "X-coordinate"))
        self.yCoorLabel.setText(_translate("MainWindow", "Y-coordinate"))
        self.displayDataButton.setStatusTip(_translate("MainWindow", "Display data"))
        self.displayDataButton.setText(_translate("MainWindow", "Display data"))
        self.loadDataButton.setStatusTip(_translate("MainWindow", "Load data to be displayed"))
        self.loadDataButton.setText(_translate("MainWindow", "Load data"))
        self.connectVideoBox.setStatusTip(_translate("MainWindow", "Check this to"))
        self.connectVideoBox.setText(_translate("MainWindow", "Connect X-coordinate to video"))
        self.displayEventsBox.setText(_translate("MainWindow", "Display events"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Display data"))
        self.videoDescLabel_2.setText(_translate("MainWindow", "Annotations and Data"))
        self.menuFIle.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.menuAnnotations.setTitle(_translate("MainWindow", "Annotations"))
        self.menuVideo.setTitle(_translate("MainWindow", "Video"))
        self.menuData.setTitle(_translate("MainWindow", "Data"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionSave.setText(_translate("MainWindow", "Save project"))
        self.actionSave_as.setText(_translate("MainWindow", "Save project as..."))
        self.actionSave_as_2.setText(_translate("MainWindow", "Save as..."))
        self.actionAutosave.setText(_translate("MainWindow", "Autosave"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionSettings_2.setText(_translate("MainWindow", "Settings"))
        self.actionSettings_3.setText(_translate("MainWindow", "Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

